
// This file has been generated by the GUI designer. Do not modify.
namespace LinearEncoderDecoderInterface
{
	public partial class ErrorWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LinearEncoderDecoderInterface.ErrorWindow
			this.Name = "LinearEncoderDecoderInterface.ErrorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ErrorWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child LinearEncoderDecoderInterface.ErrorWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.label1.UseUnderline = true;
			this.label1.Wrap = true;
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 3;
			w1.Y = 21;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
