
// This file has been generated by the GUI designer. Do not modify.
namespace LinearEncoderDecoderInterface
{
	public partial class ErrorWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LinearEncoderDecoderInterface.ErrorWindow
			this.Name = "LinearEncoderDecoderInterface.ErrorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ErrorWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
